//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cedocabar.Medicos {
	
	
	public partial class org_geografica {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.DropDownList estado;
		
		protected System.Web.UI.HtmlControls.HtmlImage Img1;
		
		protected System.Web.UI.WebControls.DropDownList municipio;
		
		protected System.Web.UI.HtmlControls.HtmlImage Img2;
		
		protected System.Web.UI.WebControls.DropDownList parroquia;
		
		protected System.Web.UI.HtmlControls.HtmlImage Img3;
		
		protected System.Web.UI.WebControls.DropDownList sector;
		
		protected System.Web.UI.HtmlControls.HtmlImage Img4;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.HtmlControls.HtmlImage Img5;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden nmbrlargo;
	}
}
