//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cedocabar.Pacientes {
	
	
	public partial class Herencia {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.CheckBox Checkbox1;
		
		protected System.Web.UI.WebControls.CheckBox Checkbox2;
		
		protected System.Web.UI.WebControls.CheckBox Checkbox4;
		
		protected System.Web.UI.WebControls.CheckBox Checkbox5;
		
		protected System.Web.UI.WebControls.CheckBox Checkbox6;
		
		protected System.Web.UI.WebControls.CheckBox Checkbox3;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText herencia;
		
		protected System.Web.UI.HtmlControls.HtmlInputText control;
	}
}
